# Generated by Django 3.0.6 on 2020-05-19 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todolistapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docomment',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='docomment', to='todolistapi.DoTitle'),
        ),
        migrations.AlterField(
            model_name='dolist',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dolist', to='todolistapi.DoTitle'),
        ),
    ]
