# Generated by Django 3.0.6 on 2020-05-19 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolistapi', '0002_auto_20200519_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='dotitle',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
